#!/usr/bin/env bash

: "${PK3S_CLI_VERSION_DEFAULT:=1.0.0}"
: "${PRODUCTIVE_K3S_CORE_VERSION_DEFAULT:=0.9.1}"
: "${PRODUCTIVE_K3S_INFRA_VERSION_DEFAULT:=0.9.41-0.9.1}"
: "${PRODUCTIVE_K3S_CORE_RELEASE_REPO_DEFAULT:=jemacchi/productive-k3s-core}"
: "${PRODUCTIVE_K3S_INFRA_RELEASE_REPO_DEFAULT:=jemacchi/productive-k3s-infra}"
